name: Backend Deploy to Render

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  statuses: write

jobs:
  run-lint:
    name: Run Super-Linter on /backend/src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: lint
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: "main"
          VALIDATE_PATHS: backend/src
          LINTER_RULES_PATH: backend/.eslintrc.json

  deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Deploy to Render via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
